/**
 * Generate HTML content for the daily transaction report
 * @param userId User ID
 * @param successfulTransactions Array of successful transactions
 * @param failedTransactions Array of failed transactions
 * @returns HTML content as string
 */
export function generateDailyReportHtml(
  userId: string,
  successfulTransactions: any[],
  failedTransactions: any[],
): string {
  const date = new Date().toLocaleDateString();
  
  // Count of transactions 
  const successCount = successfulTransactions.length;
  const failedCount = failedTransactions.length;
  const totalCount = successCount + failedCount;
  
  // Success rate
  const successRate = totalCount > 0 
    ? Math.round((successCount / totalCount) * 100) 
    : 0;
  
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Daily Transaction Report - ${date}</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      color: #333;
      line-height: 1.6;
    }
    .container {
      width: 100%;
      max-width: 600px;
      margin: 0 auto;
    }
    .header {
      background-color: #075985;
      color: white;
      padding: 20px;
      text-align: center;
    }
    .summary {
      background-color: #f8fafc;
      padding: 20px;
      margin: 20px 0;
      border-radius: 5px;
    }
    .success {
      color: #16a34a;
    }
    .failure {
      color: #dc2626;
    }
    .stats {
      display: flex;
      justify-content: space-between;
      margin-bottom: 20px;
      text-align: center;
    }
    .stat-box {
      width: 30%;
      padding: 10px;
      border-radius: 5px;
      background-color: #f1f5f9;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
    }
    th, td {
      text-align: left;
      padding: 10px;
      border-bottom: 1px solid #ddd;
    }
    th {
      background-color: #f1f5f9;
    }
    .footer {
      text-align: center;
      margin-top: 30px;
      font-size: 12px;
      color: #64748b;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Daily Transaction Report</h1>
      <p>Date: ${date}</p>
    </div>
    
    <div class="summary">
      <h2>Summary for User: ${userId}</h2>
      
      <div class="stats">
        <div class="stat-box">
          <h3>Total</h3>
          <p>${totalCount}</p>
        </div>
        <div class="stat-box success">
          <h3>Successful</h3>
          <p>${successCount}</p>
        </div>
        <div class="stat-box failure">
          <h3>Failed</h3>
          <p>${failedCount}</p>
        </div>
      </div>
      
      <p>Success Rate: <strong>${successRate}%</strong></p>
    </div>
    
    ${renderTransactionsSection('Successful Transactions', successfulTransactions, true)}
    
    ${renderTransactionsSection('Failed Transactions', failedTransactions, false)}
    
    <div class="footer">
      <p>This is an automated report generated by the Fuse API system.</p>
      <p>Please do not reply to this email.</p>
    </div>
  </div>
</body>
</html>
  `;
}

/**
 * Render a section of transactions (either successful or failed)
 */
function renderTransactionsSection(title: string, transactions: any[], isSuccess: boolean): string {
  if (transactions.length === 0) {
    return `
    <h2>${title}</h2>
    <p>No ${isSuccess ? 'successful' : 'failed'} transactions in this period.</p>
    `;
  }
  
  return `
    <h2>${title}</h2>
    <table>
      <thead>
        <tr>
          <th>Transaction ID</th>
          <th>Symbol</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Total</th>
          <th>Time</th>
        </tr>
      </thead>
      <tbody>
        ${transactions.map(tx => `
          <tr>
            <td>${tx.id || 'N/A'}</td>
            <td>${tx.symbol}</td>
            <td>${tx.quantity}</td>
            <td>$${tx.price ? tx.price.toFixed(2) : 'N/A'}</td>
            <td>$${tx.totalValue ? tx.totalValue.toFixed(2) : 'N/A'}</td>
            <td>${new Date(tx.timestamp).toLocaleString()}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  `;
} 